### PR TITLE
Update READMEs

### PR DESCRIPTION
**Pull request by Ominitay**
I forgot to commit them... Hopefully these are concise enough. Edit them if you wish! :)

### CODE REVIEW

**Comment by geefr** [comment]
No worries, I forgot as well

**Comment by Ominitay** [comment]
Hehe! I'll keep watch of the PR over at winetricks and update the readme files when it is merged.

**Comment by geefr** [comment]
Thanks a bunch, that's all wrapped up here https://github.com/geefr/beatsaber-linux-goodies/releases/tag/0.5.2

**Comment by Ominitay** [comment]
Great! In hindsight, I should have updated the workaround section as well. I'll do that when [#1599](https://github.com/Winetricks/winetricks/pull/1599) is merged.

**Pull request merged**
